# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
    - 8000:8000

    volumes:
      - ./:/app:ro
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      
    # env_file:
    #   - .env

    environment:
      - DATABASE_HOSTNAME = localhost
      - DATABASE_PORT = 5432
      - DATABASE_PASSWORD = Stivkilosjb
      - DATABASE_NAME = fastapi
      - DATABASE_USERNAME = postgres
      - SECRET_KEY = 78BVJDSHSGYCX6678BCBXCBX78EVCBNXVC63VVXVX5VCVBVB
      - ALGORITHM = HS256
      - ACCESS_TOKEN_EXPIRY_MINUTES = 30

    postgres:
      image: postgres
      environment:
      - DATABASE_PASSWORD = Stivkilosjb
      - DATABASE_DB=fastapi
    
      volumes:
      - postgres_db:/var/lib/postgresql/data

    volumes:
      postgres_db: